-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 20:37:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Buerreras
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Buerreras` ;

-- -----------------------------------------------------
-- Schema Buerreras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Buerreras` DEFAULT CHARACTER SET utf8 ;
USE `Buerreras` ;

-- -----------------------------------------------------
-- Table `Buerreras`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buerreras`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Buerreras`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `TipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buerreras`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buerreras`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `Buerreras`.`Pedidos` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `Color` VARCHAR(45) NOT NULL,
  `Cantidad_bu` VARCHAR(45) NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `Cuenta` VARCHAR(45) NOT NULL,
  `Modelo_Camioneta` VARCHAR(45) NOT NULL,
  `Cliente` VARCHAR(45) NOT NULL,
  `L` VARCHAR(45) NOT NULL,
  `ConL` VARCHAR(45) NOT NULL,
  `TipoB` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NULL,
  PRIMARY KEY (`idPedidos`),
  INDEX `fk_Pedidos_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Buerreras`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buerreras`.`ReporteVentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buerreras`.`ReporteVentas` ;

CREATE TABLE IF NOT EXISTS `Buerreras`.`ReporteVentas` (
  `idReporteVentas` INT NOT NULL AUTO_INCREMENT,
  `PDF` VARCHAR(200) NOT NULL,
  `Pedidos_idPedidos` INT NULL,
  PRIMARY KEY (`idReporteVentas`),
  INDEX `fk_ReporteVentas_Pedidos1_idx` (`Pedidos_idPedidos` ASC) VISIBLE,
  CONSTRAINT `fk_ReporteVentas_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos`)
    REFERENCES `Buerreras`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buerreras`.`Materiales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buerreras`.`Materiales` ;

CREATE TABLE IF NOT EXISTS `Buerreras`.`Materiales` (
  `idMateriales` INT NOT NULL AUTO_INCREMENT,
  `NombreMateial` VARCHAR(45) NOT NULL,
  `Cantidad` VARCHAR(45) NOT NULL,
  `Precio` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NULL,
  PRIMARY KEY (`idMateriales`),
  INDEX `fk_Materiales_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Materiales_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Buerreras`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buerreras`.`ReportesMateriales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buerreras`.`ReportesMateriales` ;

CREATE TABLE IF NOT EXISTS `Buerreras`.`ReportesMateriales` (
  `idReportesMateriales` INT NOT NULL AUTO_INCREMENT,
  `NombreMaterial` VARCHAR(45) NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `Cantidad_en_inventario` VARCHAR(45) NOT NULL,
  `Materiales_NombreMaterial` VARCHAR(45) NULL,
  `Materiales_idMateriales` INT NULL,
  PRIMARY KEY (`idReportesMateriales`),
  INDEX `fk_ReportesMateriales_Materiales1_idx` (`Materiales_idMateriales` ASC) VISIBLE,
  CONSTRAINT `fk_ReportesMateriales_Materiales1`
    FOREIGN KEY (`Materiales_idMateriales`)
    REFERENCES `Buerreras`.`Materiales` (`idMateriales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buerreras`.`Burreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buerreras`.`Burreras` ;

CREATE TABLE IF NOT EXISTS `Buerreras`.`Burreras` (
  `IdBurreas` INT NOT NULL AUTO_INCREMENT,
  `Cliente` VARCHAR(45) NOT NULL,
  `Material_Ocupado` VARCHAR(100) NOT NULL,
  `Cantidad_bu` VARCHAR(45) NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `ReportesMateriales_idReportesMateriales` INT NULL,
  `ReporteVentas_idReporteVentas` INT NULL,
  PRIMARY KEY (`IdBurreas`),
  INDEX `fk_Burreras_ReportesMateriales1_idx` (`ReportesMateriales_idReportesMateriales` ASC) VISIBLE,
  INDEX `fk_Burreras_ReporteVentas1_idx` (`ReporteVentas_idReporteVentas` ASC) VISIBLE,
  CONSTRAINT `fk_Burreras_ReportesMateriales1`
    FOREIGN KEY (`ReportesMateriales_idReportesMateriales`)
    REFERENCES `Buerreras`.`ReportesMateriales` (`idReportesMateriales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Burreras_ReporteVentas1`
    FOREIGN KEY (`ReporteVentas_idReporteVentas`)
    REFERENCES `Buerreras`.`ReporteVentas` (`idReporteVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
